export { Header } from "../components/Header";
export { Hero } from "../screen/Hero";
export { Portfolio } from "../screen/Portfolio";
export { Resume } from "../screen/Resume";
export { Skill } from "../screen/Skill";
export { Contact } from "../screen/Contact";
export { Footer } from "../components/Footer";
export { Layout } from "../components/Layout";
export { Home } from "../pages/Home";   